Update travis_install_nightly

diff --git a/travis/travis_install_nightly b/travis/travis_install_nightly
--- a/travis/travis_install_nightly
+++ b/travis/travis_install_nightly
@@ -69,6 +69,13 @@ if [ "$clone_result" != "0"  ]; then
     exit $clone_result
 fi;
 
+clone_oca_dependencies /home/travis/dependencies /home/travis/build/Zanobo/joyride_odoo_models
+clone_result=$?
+if [ "$clone_result" != "0"  ]; then
+    echo "Error cloning dependencies"
+    exit $clone_result
+fi;
+
 # Expected directory structure:
 #
 #    HOME/
